### ISSUE TITLE
Log missing in frameHelper

### ISSUE THREAD

**Issue by Baldhor** [twocolors/esphome-native-api#30]
I have an issue with one of my user, I end up with an exception in:

```
    buildMessage(messageId, bytes) {
        return pb[id_to_type[messageId]].deserializeBinary(bytes);
    }
```

```
2023-12-24T09:16:37.803Z [err] [ManagerDrivers] [Driver:esphome-wizard] [PhysicalDevice:vattenfall] [Client] Received an error: TypeError: Cannot read properties of undefined (reading 'deserializeBinary')
    at PlaintextFrameHelper.buildMessage (/app/node_modules/@2colors/esphome-native-api/lib/utils/frameHelper.js:37:42)
    at PlaintextFrameHelper.deserialize (/app/node_modules/@2colors/esphome-native-api/lib/utils/plaintextFrameHelper.js:45:30)
    at PlaintextFrameHelper.onData (/app/node_modules/@2colors/esphome-native-api/lib/utils/plaintextFrameHelper.js:55:36)
    at Socket.<anonymous> (/app/node_modules/@2colors/esphome-native-api/lib/utils/plaintextFrameHelper.js:7:47)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

I suppose the problem come from an unexpected message type.
Possible to add a check + throw an exception including the messageId?

I can submit a pull request if needed.

**Comment by twocolors** [comment]
what message type received?

can show esphome config ?

**Comment by Baldhor** [comment]
I can ask the user for his ESPhome config. Currently, my main issue is I have no idea about the messageId received, the log is missing this information :)

**Comment by twocolors** [comment]
we need to think about how to do it correctly and beautifully

**Comment by twocolors** [comment]
try @2colors/esphome-native-api@1.2.9

**Comment by Baldhor** [comment]
Looking good, thank you.
To be honest, I'm unsure how fast the "user" will respond ... (he didn't to my request of yaml file).

So I close for now.
